function [allvertex,index1,index2] = stemP_find_vertex_rRNA5S_Archaeal(rna)

% The following code used a relaxed parameters
VertexBranchOne = [StemP_find_vertex_InARow(rna,6,6,17,19)];


VertexBranchTwoLayerOne = ...
    [StemP_find_vertex_InARow(rna,6, 8, 6, 7);...
    StemP_find_vertex_nPlusn(rna,6,7,2,6,0,1);...
    StemP_find_vertex_nPlusn(rna,6,7,2,5,1,2);...
    StemP_find_vertex_nPlusn(rna,6,7,1,6,1,2)];

VertexBranchTwoLayerTwo = ...
    [StemP_find_vertex_nPlusn(rna,3,5,2,4,0,2);...
    StemP_find_vertex_nPlusn(rna,3,5,3,4,0,2)];


VertexBranchThreeLayerOne = ...
    [StemP_find_vertex_InARow(rna,5,7,6,7)] ;

VertexBranchThreeLayerTwo = [...
    StemP_find_vertex_nPlusn(rna,2,4,6,2,1,0);...
    StemP_find_vertex_nPlusn(rna,2,4,8,2,1,0);...
    StemP_find_vertex_nPlusn(rna,2,4,5,2,2,1)];

Branch2= VertexCombine(VertexBranchTwoLayerOne,VertexBranchTwoLayerTwo,2,4);
Branch3 = VertexCombine(VertexBranchThreeLayerOne,VertexBranchThreeLayerTwo,2,4);


% The following code used customized refined parameters

% VertexBranchOne = [StemP_find_vertex_InARow(rna,4,6,17.82,27.5);...
%     StemP_find_vertex_nPlusn(rna,17.82,22.7,4,1,1,0)];
% 
% 
% VertexBranchTwoLayerOne = [StemP_find_vertex_nPlusn(rna,6.37,7.72,2,6,0,1);...
%     StemP_find_vertex_InARow(rna,8, 8, 6.37,7.72);...
%     StemP_find_vertex_nPlusn(rna,6.37,7.72,2,5,0,1);...
%     StemP_find_vertex_nPlusn(rna,6.37,7.72,2,5,1,2);...
%     StemP_find_vertex_nPlusn(rna,6.37,7.72,1,6,1,2);...
%     StemP_find_vertex_TwoOnePlusFour(rna,6.37,7.72)];
% 
% VertexBranchTwoLayerTwo = [StemP_find_vertex_nPlusn(rna,3.9,6.6,2,4,0,2);...
%     StemP_find_vertex_nPlusn(rna,3.9,6.6,2,2,2,4);...
%     StemP_find_vertex_nPlusn(rna,3.9,6.6,3,4,0,2)];
% 
% 
% VertexBranchThreeLayerOne = [StemP_find_vertex_InARow(rna,5,7,5.66,10.76);...
%     StemP_find_vertex_nPlusn(rna,5.66,10.76,2,2,1,1);...
%     StemP_find_vertex_nPlusn(rna,5.66,10.76,3,1,2,2);...
%     StemP_find_vertex_nPlusn(rna,5.66,10.76,3,2,1,1)] ;
% 
% VertexBranchThreeLayerTwo = [StemP_find_vertex_OnePlusFivePlusTwo(rna,2.24,3.1);...
%     StemP_find_vertex_OnePlusSixPlusTwo(rna,2.24,3.1);...
%     StemP_find_vertex_OnePlusSixPlusOne(rna,2.24,3.1);...
%     StemP_find_vertex_nPlusn(rna,2.24,3.1,8,2,1,0);...
%     StemP_find_vertex_nPlusn(rna,2.24,3.1,1,5,1,1);...
%     StemP_find_vertex_nPlusn(rna,2.24,3.1,1,8,1,1);...
%     StemP_find_vertex_nPlusn(rna,2.24,3.1,1,7,1,1);...
%     StemP_find_vertex_InARow(rna,8, 8, 2.24,3.1);];

% Branch2= VertexCombine(VertexBranchTwoLayerOne,VertexBranchTwoLayerTwo,3.46,4.26);
% Branch3 = VertexCombine(VertexBranchThreeLayerOne,VertexBranchThreeLayerTwo,2.52,3.43);


Branch2 = make_unique(Branch2);
Branch3 = make_unique(Branch3);

index1 = size(VertexBranchOne,1);
index2 = index1 + size(Branch2,1);

allvertex = [VertexBranchOne; Branch2; Branch3];


end

function[vertex] = make_unique(vertex)
temp = {};
for i = 1:size(vertex,1)
    temp{i} = mat2str(vertex{i,1});
end
[~,ind,~]=unique(temp);
vertex = vertex(ind,:);
end